### ISSUE TITLE
Repeat questions based on its priority

### ISSUE THREAD

**Issue by shah9840** [shah9840/Flash_card_app#4]
#3  __Here_ is the reference_

**Comment by sud7535** [comment]
This should not be difficult to implement. If only repetition of same deck with updated priorities is required, it can be done by replacing the callback of **maindeck()** function in the except condition with define deck function passing the deck name as argument.

Similarly, a condition can be added to return to the **maindeck** screen when all the priorities are equal to 0.

**Comment by shah9840** [comment]
_Appreciate your efforts and your contributions are be humbly welcomed._
@sud7535

**Comment by shah9840** [comment]
https://github.com/shah9840/Flash_card_app/commit/cce4525b17c9c8fc6b57f873bc7287e2e38ef264
**_Issue addressed in this commit_**

**Comment by shah9840** [comment]
@sud7535 solved the issue successfully #7
